
export enum DiscoveryStage {
  DOMAIN = 'DOMAIN',
  BOD = 'BOD',
  KPI = 'KPI',
  EPICS = 'EPICS'
}

export interface FileContext {
  name: string;
  content: string; // Base64 for images, text for others
  mimeType: string;
  size: number;
}

export interface GroundingSource {
  title: string;
  uri: string;
}

export interface ProjectMetadata {
  companyName: string;
  missionStatement: string;
  targetVertical: string;
  geography: string;
  tam: string;
  revenueModel: string;
  websiteUrls: string;
  keyCompetitors: string;
}

export interface StageVersion {
  id: string;
  timestamp: number;
  output: string;
  input: string;
  questions: string[];
  coherenceScore: number;
  searchEntryPointHtml?: string;
}

export interface StageData {
  input: string;
  output: string;
  files: FileContext[];
  urls: string[]; // New: Stage-specific reference URLs
  formatReference?: FileContext; // Optional template/format file
  status: 'pending' | 'completed' | 'error';
  questions: string[]; // Questions generated by AI
  answers: Record<string, string>; // User answers to those questions
  groundingSources?: GroundingSource[];
  searchEntryPointHtml?: string; // HTML snippet showing search queries
  versions: StageVersion[];
  coherenceScore: number;
}

export interface AppState {
  currentStage: DiscoveryStage;
  projectMetadata: ProjectMetadata;
  stages: Record<DiscoveryStage, StageData>;
}

export interface VoiceState {
  isActive: boolean;
  isListening: boolean;
  isSpeaking: boolean;
  transcript: string;
}
